### ISSUE TITLE
0.9.5 breaks Skins - every Player has the female Alex default skin.

### ISSUE THREAD

**Issue by D3nnis3n** [orbwoi/UniversalRemote#14] opened 2017-10-15 05:51 UTC
I just tried out your new version - now everyone hast the female Alex default skin. After removing your mod, it's fine.

**Comment by orbwoi** [comment] 2017-10-15 06:15
What the.. ?! Let me look at that. haha.

**Comment by orbwoi** [comment] 2017-10-15 06:42
Uhh.. are you sure? https://ibb.co/nFGjiw

**Comment by D3nnis3n** [comment] 2017-10-15 06:43
Yes. I am :D Wait for screenshot.

**Comment by orbwoi** [comment] 2017-10-15 06:45
Can you test with ONLY my mod to confirm?

**Comment by D3nnis3n** [comment] 2017-10-15 06:46
Works in SSP, not in SMP.

**Comment by D3nnis3n** [comment] 2017-10-15 06:47
Yeh, i can.

**Comment by orbwoi** [comment] 2017-10-15 07:09
I may close these bugs for now until we get some more data. I cannot reproduce the error on my machine. You should open a new bug if you find better way to reproduce it especially without optfine installed. Also, let me know if those other players see similar issues.

**Comment by D3nnis3n** [comment] 2017-10-15 07:58
I got new info. It's not server dependent.

I tried joining onto my server 30 times. Ten times i was alex. 20 Times i was my skin.
Also, it can happen while in game - you jsut suddenly change your skin and the GUI fails.

**Comment by D3nnis3n** [comment] 2017-10-15 08:17
Okay, one of my players sees me as president, while is see me as president, too. He joined five times. One time he was alex for his view, but i still do see him as his real skin. He has the gui bug as soon as he is alex. I also can join ten times to be randomly alex for me but to be seen as president for him.

See screenshot:
My view: https://ibb.co/f0b6Dw
His view: https://ibb.co/bv9RDw

Does only occur with your mod installed.

If you still think this bug does not exist, i'll just give up and cease using the mod. I tried my utmost best to show you what happend. I can't do anything more than that and this makes me angry.

There is a bug. I'm sure.

**Comment by D3nnis3n** [comment] 2017-10-15 08:20
Try joining twenty times in a row. You must be getting an alex and the gui bug at least once. :O

**Comment by orbwoi** [comment] 2017-10-15 19:59
So if I just rejoin without re-starting client or server over and over it might happen?

**Comment by D3nnis3n** [comment] 2017-10-15 20:01
Yes. And it even can happen WHILE playing ingame. Your Skin just changes to Alex and the GUI stops working after that. Sorry, i sniffed packages for networking, i did read the console, i did everything i could. But i'm done here. I know there must be an issue. I do fully understand it's fucking hard to fix issues you can't easily reproduce, but there is a point where even i stop testing and just remove the mod as it's not worth it. In the last four weeks i tested so many mods so much that i opened hundreds of issues with hundreds of valid ones. Complete *Metals Suite, Currency, Car Mod, Animania. I give my utmost best to give all info i can. But i can't get more info out of this.

I just can show you proof it does happen, but i don't know why. :(

**Comment by orbwoi** [comment] 2017-10-15 20:04
No, I understand. I have to think carefully how this might happen. I may need to just give you a test fix if I can't get it happen for myself.

...

The most likely times for this to happen are either on server join or when you teleport to/from a custom dimension. When it 'just happens' did you recently change dimensions?

**Comment by D3nnis3n** [comment] 2017-10-15 20:06
Yeh, it's just so disappointing for me. I had one of those very bad issues and after 3 days i found a way to reproduce, finally. But i can't seem to do this here.

Yes, it does happen on join.  You join and might see Alex for a short time, then get your real skin. You might immediatly see your real skin. Or you might end up as alex.

When it does happen ingame, i did not change Dimensions, no. In fact, i had this twice after i tabbed out for discord and when i came back in, i was alex. So i thought tabbing out may cause it - but that was not reproducable also. So i did NOT see the skin change. In no case. In both times, i was tabbed out of the game.

**Comment by orbwoi** [comment] 2017-10-15 20:08
Hmmmm...

When you say 'I got new info. It's not server dependent.' do you mean you see it in SSP? OR that you don't need to restart the server? You have never seen this in SSP right?

**Comment by D3nnis3n** [comment] 2017-10-15 20:12
Yes, it's not server dependent. Not restarting the server was the cause, but rejoining the game as i found out.

And yes, i did never see this occuring in SSP. Only on my PTR-Server.

**Comment by D3nnis3n** [comment] 2017-10-15 20:21
Yes, you can. Modders do that all the time with me :D

**Comment by D3nnis3n** [comment] 2017-10-15 20:25
I could even send you my pack if you want to.

**Comment by orbwoi** [comment] 2017-10-15 20:40
I have a theory... sent you a file on discord to try out.

**Comment by orbwoi** [comment] 2017-10-15 23:06
Fixed in 0.9.6! :D

**Closed by orbwoi** 2017-10-15 23:06 UTC
