### ISSUE TITLE
Universal Remote prevents going to modded dimensions

### ISSUE THREAD

**Issue by davqvist** [orbwoi/UniversalRemote#4] opened 2017-08-20 19:17 UTC
Universal Remote 0.8.1
MC 1.12.1
Forge 2459

So this took me 8 hours to track down :P Unfortunately I can't provide any logs, but with Universal Remote installed whenever I go to a modded dimension (like the Aroma1997 Mining World) the client is hung on the "Loading Terrain" screen. You have to restart the client and login again, then you are in the dimension you wanted to go. As I was getting surrounding sounds after teleporting, it seems like everything seems to work except removing the the loading screen. Happens with every cross dimensional teleporting, so Portals or Charged Porter from RFTools or commands.

**Comment by orbwoi** [comment] 2017-08-21 07:44
That's strange I specifically tested that earlier.
Let me see if I can reproduce it.
What mod pack are you using?

**Comment by orbwoi** [comment] 2017-08-21 07:52
* confirmed *
It must be been added in the last few patches since last tested that.

**Comment by orbwoi** [comment] 2017-08-21 08:28
Damn it all. I had somehow moronically set doneLoadingTerrain to true instead of false inside NetHandlerPlayClient.

Fixed in 0.8.3

**Closed by orbwoi** 2017-08-21 08:28 UTC

**Comment by davqvist** [comment] 2017-08-21 08:59
Awesome, thanks.
