### ISSUE TITLE
1.12.2 - Can't place blocks after installing your mod

### ISSUE THREAD

**Issue by D3nnis3n** [orbwoi/UniversalRemote#11] opened 2017-09-25 00:20 UTC
Hey,
when using the mod on 1.12.2 i got the Problem that placing blocks is no longer possible, as they are erased out of inventory and not placed in the world, even though the placing sound is played. I confirmed deleting your mod stops this and playing with your mod alone has this effect while playing without any mods doesn't have it.

**Comment by orbwoi** [comment] 2017-09-25 22:33
Hmm okay. No resting for 1.12.2 has happened yet. However, that is serious side effect so Ill look into it.

**Comment by D3nnis3n** [comment] 2017-09-25 22:42
Well, as most mods just work on 1.12.2 i just expected yours to do so, too.
Then i had this big problem and needed to test every Single mod.

Am 26.09.2017 00:33 schrieb "Clayborn" <notifications@github.com>:

**Comment by orbwoi** [comment] 2017-09-27 06:24
I have it working in 1.12.2 - mojang changed some stuff with no functional change. Code cleanup? But fixing it broke 1.12.1 and 1.12.0. I am going to try to find another way to fix it that works with all 1.12 versions.

**Comment by BrisingrAerowing** [comment] 2017-10-01 17:47
And on this topic (sorta), there are two other bugs likely caused by this: Forcing survival mode no matter what was selected on the world create screen, and a forge state engine corruption error.

I ended up on this mod by doing a binary search over my modlist.

**Comment by orbwoi** [comment] 2017-10-03 01:59
1.12.2 is NOT supported right now.

**Comment by D3nnis3n** [comment] 2017-10-03 04:41
I see. It's just unusal for mods to have such big Problems between Version, you might consider adding a warning to your curseforge page, if not already done. To be honest i just switched out my forge when the new Version came out and everything worked - despite this mod.

**Comment by orbwoi** [comment] 2017-10-04 19:54
It wasnt supposed to be unfixed this long. Real life day job murdered me. Im trying to make improvements so patches are less likely to break things. Just realize this mod literally rewrites parts of forge and minecraft to make remote gui even possible.

**Comment by kragnoth** [comment] 2017-10-09 12:59
My issue that I just tracked to this mod is simply that when I interact with a bed, I sleep but don't animate.  And when I go to the nether or back I get desync from server for blocks.

Very strange, but 1.12.2 does definitely seem to touch something that this mod depends on.

**Comment by orbwoi** [comment] 2017-10-15 01:18
Finally found some time. Fixed in 1.12-0.9.5! :)

**Closed by orbwoi** 2017-10-15 01:18 UTC
