### ISSUE TITLE
0.9.7 combat crash still an issue

### ISSUE THREAD

**Issue by DingoX3** [orbwoi/UniversalRemote#19] opened 2017-10-23 18:13 UTC
I really like the idea of your mod but currently it is not usable. After spending several hours disabling mods to hunt down this issue(because i had no clue this mod even had mob interactions?) I found out it was indeed UniversalRemote. Also there was no indication in the crashlogs or logs indicating it was your mod. I wish you all the best with your mod and all future projects. Thanks for adding content to the community.

full crash with other mods: https://pastebin.com/VPD9mPWX
full crash with only UniversalRemote: https://pastebin.com/RvGxMVsD

MC: 1.12.2
Forge: 2515
UniversalRemote: 0.9.7

**Comment by orbwoi** [comment] 2017-10-23 19:43
!!! Thats odd - I walked around killing monsters with no issues when I tested. Thus I thought my other changes in 0.9.7 had fixed it. Why is it different for you ... ? I will take a deeper look and see if I can guess how you are crashing with the stack trace. You probably need to remove the mod to make your game playable but please stick around so I can send you possible fixes if i can't reproduce the crash myself.

**Comment by DingoX3** [comment] 2017-10-23 19:48
No problem. I'm subscribed to this issue so I'll get any new posts. Just let me know how i can help and we can figure this out. :)

**Comment by orbwoi** [comment] 2017-10-23 21:41
That may explain it- I don't think i ever let them hit me (dodged all attacks out of habit) while testing. I'll check this when I get home.

**Comment by orbwoi** [comment] 2017-10-24 04:29
Reproduced and fixed in 0.9.8

**Closed by orbwoi** 2017-10-24 04:29 UTC
